# Generated by Django 4.2.27 on 2025-12-22 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('birth_yyMMdd', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('base_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('carry_over', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='leaves.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', '연차'), ('HALF', '반차')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_day', models.CharField(blank=True, choices=[('AM', '오전'), ('PM', '오후')], max_length=2, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('used_comp', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('used_annual', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leaves.employee')),
                ('leave_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leaves.leaveyear')),
            ],
        ),
        migrations.CreateModel(
            name='CompDayGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField()),
                ('holiday_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_grants', to='leaves.leaveyear')),
            ],
        ),
        migrations.AddIndex(
            model_name='leaveyear',
            index=models.Index(fields=['year'], name='leaves_leav_year_2f360d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveyear',
            index=models.Index(fields=['employee', 'year'], name='leaves_leav_employe_d16ca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaveyear',
            unique_together={('employee', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date'], name='leaves_leav_start_d_7483b2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['end_date'], name='leaves_leav_end_dat_be12b0_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date'], name='leaves_leav_employe_7c5f34_idx'),
        ),
        migrations.AddIndex(
            model_name='compdaygrant',
            index=models.Index(fields=['worked_date'], name='leaves_comp_worked__af87da_idx'),
        ),
    ]
