# Generated by Django 4.2.27 on 2025-12-22 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDayUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='leaves.compdaygrant')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_uses', to='leaves.leaverequest')),
            ],
            options={
                'indexes': [models.Index(fields=['leave_request'], name='leaves_comp_leave_r_cc921c_idx'), models.Index(fields=['grant'], name='leaves_comp_grant_i_86a481_idx')],
            },
        ),
    ]
