# Generated by Django 4.2.27 on 2025-12-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_compdayuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_date', models.DateField(db_index=True)),
                ('title', models.CharField(default='메모', max_length=60)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['memo_date'], name='leaves_cale_memo_da_215fc8_idx')],
            },
        ),
    ]
