# Generated by Django 4.2.27 on 2026-01-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_calendarmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmemo',
            name='color',
            field=models.CharField(choices=[('green', '녹색'), ('blue', '파랑'), ('yellow', '노랑'), ('red', '빨강'), ('gray', '회색')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='calendarmemo',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
